name: BaseImage Builder

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Choose BaseImage to be created'
        required: true
        type: choice
        options:
          - '---choose---'
          - 'CADDY'
          - 'MARIADB'
          - 'NGINX'
          - 'PHP-FPM'

jobs:
  file_exists:
    name: Check Required Files
    runs-on: ubuntu-latest
    outputs:
      files_exist: ${{ steps.check_files.outputs.files_exist }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check for .env and docker-compose.yml
        id: check_files
        run: |
          files=(.env docker-compose.yml demo.io)
          file_exists=true
          
          for file in "${files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "required file $file does not exist"
              file_exists=false
              break
            fi
          done
          
          if [ "$file_exists" = false ]; then
            echo "files_exist=false" >> $GITHUB_ENV
            exit 1
          else
            echo "files_exist=true" >> $GITHUB_ENV
          fi

  check-tag:
    name: Verify Image Tag
    runs-on: ubuntu-latest
    outputs:
      tag_exists: ${{ steps.check_tag.outputs.tag_exists }}
    needs: precondition
    if: needs.precondition.outputs.files_exist == 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Approve if tag does not exist
        id: check_tag
        run: |
          set -o allexport
          source .env
          set +o allexport
          
          STAGE="${{ github.event.inputs.stage }}"
          IMAGE_NAME_VAR="${STAGE}_IMAGE_NAME"
          IMAGE_TAG_VAR="${STAGE}_IMAGE_TAG"
          
          IMAGE_NAME="${!IMAGE_NAME_VAR}"
          IMAGE_TAG="${!IMAGE_TAG_VAR}"
          
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          
          tag_exist=true          
          if docker manifest inspect ${DOCKER_NAMESPACE}/${IMAGE_NAME_LOWER}:${IMAGE_TAG} > /dev/null >&1; then
            echo "tag_exist=true" >> $GITHUB_ENV
            echo "TAG ${IMAGE_TAG} for IMAGE ${IMAGE_NAME_LOWER} already exists"
            exit 1
          else
            echo "tag_exist=true" >> $GITHUB_ENV
            echo "TAG ${IMAGE_TAG} for IMAGE ${IMAGE_NAME_LOWER} does not exist"
          fi

  build_and_push:
    name: Build and Push to Registry
    runs-on: ubuntu-latest
    needs: check-tag
    if: needs.precondition.outputs.tag_exist == 'true'
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          set -o allexport
          source .env
          set +o allexport
          
          STAGE="${{ github.event.inputs.stage }}"
          STAGE_LOWER=$(echo "$STAGE" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME_VAR="${STAGE}_IMAGE_NAME"
          IMAGE_TAG_VAR="${STAGE}_IMAGE_TAG"
          
          IMAGE_NAME="${!IMAGE_NAME_VAR}"
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          
          IMAGE_TAG="${!IMAGE_TAG_VAR}"
          
          echo "Building Docker image..."
          docker compose -f docker-compose.yml build --no-cache --force-rm ${STAGE_LOWER}
          
          # echo "Tagging Docker image..."
          # docker tag ${STAGE_LOWER} ${DOCKER_NAMESPACE}/${IMAGE_NAME_LOWER}:${IMAGE_TAG}
          
          echo "Pushing Docker image to Docker Hub..."
          docker image push ${DOCKER_NAMESPACE}/${IMAGE_NAME_LOWER}:${IMAGE_TAG}
