name: BaseImage Builder

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Choose build stage to run'
        required: true
        type: choice
        options:
          - '---choose---'
          - 'CADDY'

jobs:
  check-tag:
    name: verify image tag
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: verify tag
        run: |
          set -o allexport
          source .env
          set +o allexport
          D_IMAGE_NAME="${ env.inputs.stag }_IMAGE_NAME"
          eval IMAGE_NAME=\$D_IMAGE_NAME
          D_IMAGE_TAG="${ env.inputs.stag }_IMAGE_NAME"
          eval IMAGE_TAG=\$D_IMAGE_TAG
          TAG_EXISTS=$(curl -s -o /dev/null -w "%{http_code}" https://hub.docker.com/v2/repositories/${DOCKER_NAMESPACE}/${{ IMAGE_NAME }}/tags/${{ IMAGE_TAG }})
          if [ "$TAG_EXISTS" -eq "200" ]; then
            echo "TAG ${{ IMAGE_TAG }} for IMAGE ${{ IMAGE_NAME }} already exists"
            exit 1
          else
            echo "TAG ${{ IMAGE_TAG }} for IMAGE ${{ IMAGE_NAME }} does not exist"
          fi
