name: Caddy Image Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    needs: BaseImage Builder
    strategy:
      matrix:
        stage: [CADDY]
    steps:
      - name: Set STAGE Environment Variable
        run: echo "STAGE=CADDY" >> $GITHUB_ENV

      - name: Run Shared Steps
        uses: ./.github/workflows/workflow.yml